#if !canImport(ObjectiveC)
import XCTest

extension AddressControllerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AddressControllerTests = [
        ("testEndpoints", testEndpoints),
    ]
}

extension AppTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AppTests = [
        ("testUniverseWorks", testUniverseWorks),
    ]
}

extension GoogleMapsAddressValidatorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GoogleMapsAddressValidatorTests = [
        ("testBuildingAddress", testBuildingAddress),
        ("testNonExistant", testNonExistant),
        ("testState", testState),
        ("testStreetAddress", testStreetAddress),
    ]
}

extension MySQLAddressRepositoryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MySQLAddressRepositoryTests = [
        ("testOperations", testOperations),
    ]
}

extension MySQLDatabaseIsolationLevelTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MySQLDatabaseIsolationLevelTests = [
        ("testCases", testCases),
        ("testCurrent", testCurrent),
        ("testIsolatedTransaction", testIsolatedTransaction),
        ("testParse", testParse),
        ("testQuery", testQuery),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AddressControllerTests.__allTests__AddressControllerTests),
        testCase(AppTests.__allTests__AppTests),
        testCase(GoogleMapsAddressValidatorTests.__allTests__GoogleMapsAddressValidatorTests),
        testCase(MySQLAddressRepositoryTests.__allTests__MySQLAddressRepositoryTests),
        testCase(MySQLDatabaseIsolationLevelTests.__allTests__MySQLDatabaseIsolationLevelTests),
    ]
}
#endif
